### PR TITLE
fix(site): make demo response scrollable

### PR DESCRIPTION
**Pull request by Effiti**
https://user-images.githubusercontent.com/48206628/156936568-ee3d57f0-776c-46ef-8c30-74f7584b3eda.mp4

https://i.imgur.com/mXBpTdE.png

in chrome this is seemingly set automatically, but in firefox we have to explicitly state it, using tailwinds `overflow-auto`

### CODE REVIEW

**Comment by ijemmao** [comment]
@Effiti I'm unable to reproduce the error both on local and production. Can you attach a video of the bug that you're fixing?

**Comment by Effiti** [comment]
> @Effiti I'm unable to reproduce the error both on local and production. Can you attach a video of the bug that you're fixing?

huh.. weird! 



https://user-images.githubusercontent.com/48206628/156823796-53936b34-1a1b-4832-8db5-6853c3648bcf.mp4



(testing on linux, using `Mozilla Firefox 97.0.1`, originally tested on `LibreWolf LibreWolf 97.0.1`

**Comment by ijemmao** [comment]
@Effiti that's interesting! can you update your PR description with the video that's including the fix? I'm running on Mac OSX with Chrome version 98.0.4758.80 and I'm not seeing that issue on my end

**Comment by Effiti** [comment]
@ijemmao just added an image now, hope that's enough!

**Comment by ijemmao** [comment]
> @ijemmao just added an image now, hope that's enough!

@Effiti a video would be ideal!

**Comment by Effiti** [comment]
@ijemmao like that?

**Review by ijemmao — APPROVED** [review]
lgtm, great work!

**Pull request merged**
