### PR TITLE
feat: Validate wordClass fields with WordClass Constants

### PR DESCRIPTION
**Pull request by Ebugo**

### CODE REVIEW

**Review by ijemmao — CHANGES_REQUESTED** [review]
Using a validation hook is a great idea of consistency.

The only thing that you'll need to do is update all the JSON objects in the project so that not only tests start working again but also the populate script that used for development also works.

Also, please provide a description of the work that you did in this PR

**Comment by Ebugo** [comment]
> Using a validation hook is a great idea of consistency.
> 
> The only thing that you'll need to do is update all the JSON objects in the project so that not only tests start working again but also the populate script that used for development also works.
> 
> Also, please provide a description of the work that you did in this PR

yes, can we talk more about this?

**Comment by ijemmao** [comment]
You can leave your questions here @Ebugo

**Comment by ijemmao** [comment]
Closing due to inactivity. Feel free to reopen if there's an update.

**Pull request closed without merging**
